# Site settings
title: Steven Wu
description: Website Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://steveu14.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Steven Wu
user_description: I'm a Data Scientist
email: stevenwu3084@gmail.com
# twitter_username: lorem_ipsum
linkedin_username: stevenwu14
github_username:  steveu14
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

